# Generated by Django 3.0.8 on 2020-08-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('imagePath', models.CharField(max_length=100)),
                ('shipped', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Ingredient',
            },
        ),
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('headline', models.CharField(max_length=200)),
                ('websiteUrl', models.URLField()),
                ('imagePath', models.CharField(max_length=100)),
                ('downloaded_img', models.ImageField(blank=True, upload_to='')),
                ('ingredients', models.ManyToManyField(to='what_can_i_cook.Ingredient')),
            ],
            options={
                'verbose_name': 'Recipe',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='what_can_i_cook.IngredientGroup'),
        ),
    ]
