# Generated by Django 3.0.8 on 2020-08-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_can_i_cook', '0002_auto_20200809_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
