# Generated by Django 3.0.8 on 2020-08-13 20:35
# Populates the Ingredients with their Groupname.

from django.db import migrations
from what_can_i_cook.utils.seed_database_part2 import main as util_main

def add_group_data_to_ing(apps, schema_editor):
    util_main()

class Migration(migrations.Migration):

    dependencies = [
        ('what_can_i_cook', '0003_ingredient_group'),
    ]

    operations = [
        migrations.RunPython(add_group_data_to_ing),
    ]
